# Generated by Django 3.2.6 on 2021-08-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YearRoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('max_time', models.DateTimeField()),
                ('min_people', models.IntegerField()),
                ('min_time', models.DateTimeField()),
                ('avg_people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='WeekRoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('max_time', models.DateTimeField()),
                ('min_people', models.IntegerField()),
                ('min_time', models.DateTimeField()),
                ('avg_people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='MonthRoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('max_time', models.DateTimeField()),
                ('min_people', models.IntegerField()),
                ('min_time', models.DateTimeField()),
                ('avg_people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('n_people', models.IntegerField(default=0, verbose_name='number or people')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.camera')),
            ],
        ),
        migrations.CreateModel(
            name='DayRoomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('max_time', models.DateTimeField()),
                ('min_people', models.IntegerField()),
                ('min_time', models.DateTimeField()),
                ('avg_people', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.room')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cam_api.room'),
        ),
    ]
