# Generated by Django 3.2.6 on 2021-09-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
