# Generated by Django 3.2.6 on 2021-09-02 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cam_api', '0002_rename_timestamp_logs_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='datetime',
        ),
        migrations.AddField(
            model_name='logs',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
