# Generated by Django 3.2.6 on 2021-09-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam_api', '0004_auto_20210903_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekroomstats',
            name='room',
        ),
        migrations.RemoveField(
            model_name='yearroomstats',
            name='room',
        ),
        migrations.DeleteModel(
            name='MonthRoomStats',
        ),
        migrations.DeleteModel(
            name='WeekRoomStats',
        ),
        migrations.DeleteModel(
            name='YearRoomStats',
        ),
    ]
